//
// AccountIsNFT.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountIsNFT: Codable, JSONEncodable, Hashable {

    public var isNft: Bool

    public init(isNft: Bool) {
        self.isNft = isNft
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isNft = "is_nft"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isNft, forKey: .isNft)
    }
}

