//
// AccountIsCandyMachine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountIsCandyMachine: Codable, Hashable {

    public var isCandyMachine: Bool

    public init(isCandyMachine: Bool) {
        self.isCandyMachine = isCandyMachine
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isCandyMachine = "is_candy_machine"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isCandyMachine, forKey: .isCandyMachine)
    }
}

