//
// Account.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Account: Codable, Hashable {

    public var context: AccountContext?
    public var value: AccountValue?

    public init(context: AccountContext? = nil, value: AccountValue? = nil) {
        self.context = context
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case context
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

