//
// AirdropRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AirdropRequest: Codable, Hashable {

    /** The address to which to send the airdrop of 0.015 SOL */
    public var recipientAddress: String

    public init(recipientAddress: String) {
        self.recipientAddress = recipientAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipientAddress = "recipient_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipientAddress, forKey: .recipientAddress)
    }
}

