//
// CandyMachineSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CandyMachineSearchResponse: Codable, Hashable {

    /** The config address of the candy machine */
    public var configAddress: String

    public init(configAddress: String) {
        self.configAddress = configAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configAddress = "config_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(configAddress, forKey: .configAddress)
    }
}

