//
// CCProjectCreateRequestPayoutMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The method by which we pay out earnings to you. Currently, we only support paying out directly to your Solana wallet. In the future, we will support other wallets and support bank payouts.  */
public struct CCProjectCreateRequestPayoutMethod: Codable, JSONEncodable, Hashable {

    /** The identifier of the wallet that will receive the payments. On Solana, this is your wallet's public key.   */
    public var blockchainIdentifier: String

    public init(blockchainIdentifier: String) {
        self.blockchainIdentifier = blockchainIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockchainIdentifier = "blockchain_identifier"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockchainIdentifier, forKey: .blockchainIdentifier)
    }
}

