//
// CCWebhookValidateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CCWebhookValidateRequest: Codable, JSONEncodable, Hashable {

    /** The unique identifier of the webhook.  */
    public var webhookId: String
    /** The signature we inluded in the webhook. The signature is from the Blockchain API and it ensures that the webhook is from us and not a malicioius actor.  */
    public var webhookSignature: AnyCodable
    /** The time the webhook was sent.  */
    public var timeSent: Double

    public init(webhookId: String, webhookSignature: AnyCodable, timeSent: Double) {
        self.webhookId = webhookId
        self.webhookSignature = webhookSignature
        self.timeSent = timeSent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookId = "webhook_id"
        case webhookSignature = "webhook_signature"
        case timeSent = "time_sent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(webhookId, forKey: .webhookId)
        try container.encode(webhookSignature, forKey: .webhookSignature)
        try container.encode(timeSent, forKey: .timeSent)
    }
}

