//
// DoubleTransferResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DoubleTransferResponse: Codable {
    case typeTransferResponse(TransferResponse)
    case typeTransferResponseCompiled(TransferResponseCompiled)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTransferResponse(let value):
            try container.encode(value)
        case .typeTransferResponseCompiled(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TransferResponse.self) {
            self = .typeTransferResponse(value)
        } else if let value = try? container.decode(TransferResponseCompiled.self) {
            self = .typeTransferResponseCompiled(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of DoubleTransferResponse"))
        }
    }
}

