//
// GeneralAirdropRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeneralAirdropRequest: Codable, JSONEncodable, Hashable {

    /** The address/public key to which to send the airdrop.  Examples: - Solana: `GKNcUmNacSJo4S2Kq3DuYRYRGw3sNUfJ4tyqd198t6vQ` - Ethereum: `0xa84b9478d203cd25dF722e83C87590f8028f6aAA` */
    public var recipientBlockchainIdentifier: String

    public init(recipientBlockchainIdentifier: String) {
        self.recipientBlockchainIdentifier = recipientBlockchainIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipientBlockchainIdentifier = "recipient_blockchain_identifier"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipientBlockchainIdentifier, forKey: .recipientBlockchainIdentifier)
    }
}

