//
// GenerateSeedPhraseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateSeedPhraseRequest: Codable, JSONEncodable, Hashable {

    /** The number of words to generate. Must be one of: 12, 15, 18, 21, or 24. Avalanche's default is 24. All other chains we support default to 12.  */
    public var nWords: Double?

    public init(nWords: Double? = nil) {
        self.nWords = nWords
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nWords = "n_words"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nWords, forKey: .nWords)
    }
}

