//
// GeneralFeePayerWallet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This feature is only supported for &#x60;solana&#x60;.  If you do NOT provide a wallet here, the fee payer of the transaction will be the &#x60;wallet&#x60; you provide or the &#x60;sender_blockchain_identifier&#x60;.        If you do provide a wallet, then the &#x60;fee_payer_wallet&#x60; will pay the fees of the transaction and any costs associated with creating a new associated token account (only if necessary; approx. 0.002 SOL when necessary). A new account is necessary if you are sending an NFT or SPL token to a user that has not received the same NFT or one of the SPL tokens before (thus, a new associated token account is needed). */
public enum GeneralFeePayerWallet: Codable, JSONEncodable, Hashable {
    case typeGeneralB58PrivateKey(GeneralB58PrivateKey)
    case typeGeneralPrivateKey(GeneralPrivateKey)
    case typeGeneralSecretRecoveryPhrase(GeneralSecretRecoveryPhrase)
    case typeHexPrivateKey(HexPrivateKey)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeGeneralB58PrivateKey(let value):
            try container.encode(value)
        case .typeGeneralPrivateKey(let value):
            try container.encode(value)
        case .typeGeneralSecretRecoveryPhrase(let value):
            try container.encode(value)
        case .typeHexPrivateKey(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(GeneralB58PrivateKey.self) {
            self = .typeGeneralB58PrivateKey(value)
        } else if let value = try? container.decode(GeneralPrivateKey.self) {
            self = .typeGeneralPrivateKey(value)
        } else if let value = try? container.decode(GeneralSecretRecoveryPhrase.self) {
            self = .typeGeneralSecretRecoveryPhrase(value)
        } else if let value = try? container.decode(HexPrivateKey.self) {
            self = .typeHexPrivateKey(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GeneralFeePayerWallet"))
        }
    }
}

