//
// GeneralTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GeneralTransaction: Codable, JSONEncodable, Hashable {
    case typeEthereumTransaction(EthereumTransaction)
    case typeSolanaTransaction(SolanaTransaction)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeEthereumTransaction(let value):
            try container.encode(value)
        case .typeSolanaTransaction(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(EthereumTransaction.self) {
            self = .typeEthereumTransaction(value)
        } else if let value = try? container.decode(SolanaTransaction.self) {
            self = .typeSolanaTransaction(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GeneralTransaction"))
        }
    }
}

