//
// GetAllNFTsResponseUnminted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAllNFTsResponseUnminted: Codable, Hashable {

    /** The name of the unminted NFT */
    public var name: String?
    /** The uri of the unminted NFT */
    public var uri: String?

    public init(name: String? = nil, uri: String? = nil) {
        self.name = name
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(uri, forKey: .uri)
    }
}

