//
// GetAllNFTsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAllNFTsResponse: Codable, Hashable {

    public var mintedNfts: [GetAllNFTsResponseMintedNfts]?
    public var unmintedNfts: [GetAllNFTsResponseUnmintedNfts]?

    public init(mintedNfts: [GetAllNFTsResponseMintedNfts]? = nil, unmintedNfts: [GetAllNFTsResponseUnmintedNfts]? = nil) {
        self.mintedNfts = mintedNfts
        self.unmintedNfts = unmintedNfts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mintedNfts = "minted_nfts"
        case unmintedNfts = "unminted_nfts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mintedNfts, forKey: .mintedNfts)
        try container.encodeIfPresent(unmintedNfts, forKey: .unmintedNfts)
    }
}

