//
// GetCandyMetadataResponseCreators.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCandyMetadataResponseCreators: Codable, JSONEncodable, Hashable {

    /** The public key of a creator */
    public var address: String?
    /** The share of the royalty that each creator receives */
    public var share: Double?

    public init(address: String? = nil, share: Double? = nil) {
        self.address = address
        self.share = share
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case share
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(share, forKey: .share)
    }
}

