//
// InputBlockchainIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InputBlockchainIdentifier: Codable, JSONEncodable, Hashable {

    public var blockchainIdentifier: String?

    public init(blockchainIdentifier: String? = nil) {
        self.blockchainIdentifier = blockchainIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockchainIdentifier = "blockchain_identifier"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blockchainIdentifier, forKey: .blockchainIdentifier)
    }
}

