//
// ListNFTsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListNFTsResponse: Codable, Hashable {

    /** A list of mint addresses represented by a string */
    public var nftsOwned: [String]?
    /** A list of the dictionaries, where each dictionary is an NFT's metadata */
    public var nftsMetadata: [NFT]?

    public init(nftsOwned: [String]? = nil, nftsMetadata: [NFT]? = nil) {
        self.nftsOwned = nftsOwned
        self.nftsMetadata = nftsMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nftsOwned = "nfts_owned"
        case nftsMetadata = "nfts_metadata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nftsOwned, forKey: .nftsOwned)
        try container.encodeIfPresent(nftsMetadata, forKey: .nftsMetadata)
    }
}

