//
// NFTAnalyticsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NFTAnalyticsRequest: Codable, JSONEncodable, Hashable {

    /** The list of mint addresses. Each address must be a valid public key. */
    public var mintAddresses: [String]
    /** Response will not include transactions before `start_time`. Set this to `-1` in order to get the entire history we have stored.  */
    public var startTime: Double?
    /** Response will not include transactions after `end_time`   */
    public var endTime: Double?

    public init(mintAddresses: [String], startTime: Double? = nil, endTime: Double? = nil) {
        self.mintAddresses = mintAddresses
        self.startTime = startTime
        self.endTime = endTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mintAddresses = "mint_addresses"
        case startTime = "start_time"
        case endTime = "end_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mintAddresses, forKey: .mintAddresses)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
    }
}

