//
// NFTCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NFTCollection: Codable, JSONEncodable, Hashable {

    /** A `0` or `1` indicating whether or not the associated collection is verified.  */
    public var verified: Double?
    /** Will return `11111111111111111111111111111111` if no associated `collection_id`. Otherwise it will return the `collection_id`, which is a public key representing the verified Metaplex collection. See more [here](https://collections.metaplex.com).  */
    public var key: String?

    public init(verified: Double? = nil, key: String? = nil) {
        self.verified = verified
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verified
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(verified, forKey: .verified)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

