//
// ParameterSpecification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParameterSpecification: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case string = "string"
        case number = "number"
        case boolean = "boolean"
        case array = "array"
    }
    /** The type of the parameter */
    public var type: ModelType?
    /** The name of the parameter */
    public var name: String?
    /** The name of the parameter */
    public var description: String?
    /** Whether or not this parameter is required */
    public var _required: Bool?

    public init(type: ModelType? = nil, name: String? = nil, description: String? = nil, _required: Bool? = nil) {
        self.type = type
        self.name = name
        self.description = description
        self._required = _required
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case description
        case _required = "required"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(_required, forKey: ._required)
    }
}

