//
// SolSeaListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SolSeaListRequest: Codable, Hashable {

    public var wallet: Wallet
    /**  The number of lamports you are expecting to sell the NFT for.  There are 1e9 (1 billion) Lamports in a SOL.    Min price: 1   Max price: 18446744073709551615  */
    public var nftPrice: Double

    public init(wallet: Wallet, nftPrice: Double) {
        self.wallet = wallet
        self.nftPrice = nftPrice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case wallet
        case nftPrice = "nft_price"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(wallet, forKey: .wallet)
        try container.encode(nftPrice, forKey: .nftPrice)
    }
}

