//
// Task.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Task: Codable, Hashable {

    public var response: AnyCodable
    public var timeCompleted: Double?
    public var statusCode: Double

    public init(response: AnyCodable, timeCompleted: Double? = nil, statusCode: Double) {
        self.response = response
        self.timeCompleted = timeCompleted
        self.statusCode = statusCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case response
        case timeCompleted = "time_completed"
        case statusCode = "status_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(response, forKey: .response)
        try container.encodeIfPresent(timeCompleted, forKey: .timeCompleted)
        try container.encode(statusCode, forKey: .statusCode)
    }
}

