//
// Wallet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The wallet authentication information required to sign transactions.  Click the &#x60;&gt;&#x60; arrow next to \&quot;wallet\&quot; on the left to see more details. See our Security section &lt;a href&#x3D;\&quot;#section/Security\&quot;&gt;here&lt;/a&gt;.  */
public enum Wallet: Codable {
    case typeB58PrivateKey(B58PrivateKey)
    case typePrivateKey(PrivateKey)
    case typeSecretRecoveryPhrase(SecretRecoveryPhrase)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeB58PrivateKey(let value):
            try container.encode(value)
        case .typePrivateKey(let value):
            try container.encode(value)
        case .typeSecretRecoveryPhrase(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(B58PrivateKey.self) {
            self = .typeB58PrivateKey(value)
        } else if let value = try? container.decode(PrivateKey.self) {
            self = .typePrivateKey(value)
        } else if let value = try? container.decode(SecretRecoveryPhrase.self) {
            self = .typeSecretRecoveryPhrase(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of Wallet"))
        }
    }
}

