name: theblockchainapi
targets:
  theblockchainapi:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [theblockchainapi]
    info:
      path: ./Info.plist
      version: null
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
