//
// ListNFTsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListNFTsRequest: Codable, Hashable {

    public enum Network: String, Codable, CaseIterable {
        case devnet = "devnet"
        case mainnetBeta = "mainnet-beta"
    }
    /** The public key of the account whose list of owned NFTs you want to get   */
    public var publicKey: String
    public var network: Network? = .devnet

    public init(publicKey: String, network: Network? = .devnet) {
        self.publicKey = publicKey
        self.network = network
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publicKey = "public_key"
        case network
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publicKey, forKey: .publicKey)
        try container.encodeIfPresent(network, forKey: .network)
    }
}

