//
// UploadFileRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UploadFileRequest: Codable, Hashable {

    public enum UploadMethod: String, Codable, CaseIterable {
        case ipfs = "IPFS"
        case arweave = "Arweave"
        case filecoin = "Filecoin"
    }
    public var uploadMethod: UploadMethod? = .ipfs

    public init(uploadMethod: UploadMethod? = .ipfs) {
        self.uploadMethod = uploadMethod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uploadMethod = "upload_method"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uploadMethod, forKey: .uploadMethod)
    }
}

